FROM openjdk
WORKDIR src/lib
ADD ./target/dashboard_eureka_server-0.0.1-SNAPSHOT.jar /src/lib/dashboard_eureka_server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","dashboard_eureka_server-0.0.1-SNAPSHOT.jar"]