version: "3.3"

services:
  productservice:
    image: product_image
    container_name: product_container
    build: Rest_mongo_Product/
    restart: always
    network_mode: host
    ports:
      - 5656:5656
    depends_on:
      - mongoservice
      - eurekaservice

  mongoservice:
    image: mongo:3.4-jessie
    container_name: mongo_container
    network_mode: host
    ports:
      - 27017:27017


  authservice:
    image: auth_image
    container_name: auth_container
    build: authenticationWithRest/
    restart: always
    network_mode: host
    ports:
      - 7979:7979
    depends_on:
      - mysqlservice
      - eurekaservice

  mysqlservice:
      image: mysql:5.5
      container_name: mysql_container
      network_mode: host
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USERNAME: user
        MYSQL_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apiservice:
    image: api_img
    container_name: api_container
    build: apigwdemo/
    network_mode: host
    ports:
      - 1111:1111


  eurekaservice:
    image: eureka_image
    container_name: eureka_container
    build: dashboard_eureka_server/
    network_mode: host
    ports:
      - 8761:8761


